/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import bean.DanhMucBean;
import controller.ChuyenManHinhController;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ASUS
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setTitle("Phần mềm quản lý cửa hàng ô tô");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logo.png")));
        
        ChuyenManHinhController chuyenManHinhController = new ChuyenManHinhController(jPnView);
        chuyenManHinhController.setView(jPnBanHang, jLbBanHang);
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("BanHang", jPnBanHang, jLbBanHang));         
        listItem.add(new DanhMucBean("NhaCungCap", jPnNhaCungCap, jLbNhaCungCap));  
        listItem.add(new DanhMucBean ("LoaiSanPham", jPnLoaiSP, jLbLoaiSP));
       
        listItem.add(new DanhMucBean("SanPham", jPnSanPham, jLbSanPham));
        listItem.add(new DanhMucBean("NhanVien", jPnNhanVien, jLbNhanVien));        
        listItem.add(new DanhMucBean("KhachHang", jPnKhachHang, jLbKhachHang));        
        listItem.add(new DanhMucBean("NhapHang", jPnNhapHang, jLbNhapHang));
        listItem.add(new DanhMucBean("ThongKe", jPnThongKe, jLbThongKe));

        
        chuyenManHinhController.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnRoot = new javax.swing.JPanel();
        jPnMenu = new javax.swing.JPanel();
        jPnBanHang = new javax.swing.JPanel();
        jLbBanHang = new javax.swing.JLabel();
        jPnSanPham = new javax.swing.JPanel();
        jLbSanPham = new javax.swing.JLabel();
        jPnNhanVien = new javax.swing.JPanel();
        jLbNhanVien = new javax.swing.JLabel();
        jPnKhachHang = new javax.swing.JPanel();
        jLbKhachHang = new javax.swing.JLabel();
        jPnNhapHang = new javax.swing.JPanel();
        jLbNhapHang = new javax.swing.JLabel();
        jPnThongKe = new javax.swing.JPanel();
        jLbThongKe = new javax.swing.JLabel();
        jPnNhaCungCap = new javax.swing.JPanel();
        jLbNhaCungCap = new javax.swing.JLabel();
        jPnLoaiSP = new javax.swing.JPanel();
        jLbLoaiSP = new javax.swing.JLabel();
        jPnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnMenu.setBackground(new java.awt.Color(33, 46, 52));

        jPnBanHang.setBackground(new java.awt.Color(76, 175, 80));

        jLbBanHang.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbBanHang.setForeground(new java.awt.Color(255, 255, 255));
        jLbBanHang.setText("Bán hàng");

        javax.swing.GroupLayout jPnBanHangLayout = new javax.swing.GroupLayout(jPnBanHang);
        jPnBanHang.setLayout(jPnBanHangLayout);
        jPnBanHangLayout.setHorizontalGroup(
            jPnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnBanHangLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLbBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPnBanHangLayout.setVerticalGroup(
            jPnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPnSanPham.setBackground(new java.awt.Color(76, 175, 80));

        jLbSanPham.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbSanPham.setForeground(new java.awt.Color(255, 255, 255));
        jLbSanPham.setText("Sản phẩm");

        javax.swing.GroupLayout jPnSanPhamLayout = new javax.swing.GroupLayout(jPnSanPham);
        jPnSanPham.setLayout(jPnSanPhamLayout);
        jPnSanPhamLayout.setHorizontalGroup(
            jPnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnSanPhamLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnSanPhamLayout.setVerticalGroup(
            jPnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnSanPhamLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPnNhanVien.setBackground(new java.awt.Color(76, 175, 80));

        jLbNhanVien.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jLbNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout jPnNhanVienLayout = new javax.swing.GroupLayout(jPnNhanVien);
        jPnNhanVien.setLayout(jPnNhanVienLayout);
        jPnNhanVienLayout.setHorizontalGroup(
            jPnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnNhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPnNhanVienLayout.setVerticalGroup(
            jPnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPnKhachHang.setBackground(new java.awt.Color(76, 175, 80));

        jLbKhachHang.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jLbKhachHang.setText("Khách hàng");

        javax.swing.GroupLayout jPnKhachHangLayout = new javax.swing.GroupLayout(jPnKhachHang);
        jPnKhachHang.setLayout(jPnKhachHangLayout);
        jPnKhachHangLayout.setHorizontalGroup(
            jPnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnKhachHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPnKhachHangLayout.setVerticalGroup(
            jPnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPnNhapHang.setBackground(new java.awt.Color(76, 175, 80));

        jLbNhapHang.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbNhapHang.setForeground(new java.awt.Color(255, 255, 255));
        jLbNhapHang.setText("Nhân viên");

        javax.swing.GroupLayout jPnNhapHangLayout = new javax.swing.GroupLayout(jPnNhapHang);
        jPnNhapHang.setLayout(jPnNhapHangLayout);
        jPnNhapHangLayout.setHorizontalGroup(
            jPnNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnNhapHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPnNhapHangLayout.setVerticalGroup(
            jPnNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnNhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPnThongKe.setBackground(new java.awt.Color(76, 175, 80));

        jLbThongKe.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbThongKe.setForeground(new java.awt.Color(255, 255, 255));
        jLbThongKe.setText("Thống kê");

        javax.swing.GroupLayout jPnThongKeLayout = new javax.swing.GroupLayout(jPnThongKe);
        jPnThongKe.setLayout(jPnThongKeLayout);
        jPnThongKeLayout.setHorizontalGroup(
            jPnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongKeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnThongKeLayout.setVerticalGroup(
            jPnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPnNhaCungCap.setBackground(new java.awt.Color(76, 175, 80));

        jLbNhaCungCap.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbNhaCungCap.setForeground(new java.awt.Color(255, 255, 255));
        jLbNhaCungCap.setText("Nhà cung cấp");

        javax.swing.GroupLayout jPnNhaCungCapLayout = new javax.swing.GroupLayout(jPnNhaCungCap);
        jPnNhaCungCap.setLayout(jPnNhaCungCapLayout);
        jPnNhaCungCapLayout.setHorizontalGroup(
            jPnNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnNhaCungCapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPnNhaCungCapLayout.setVerticalGroup(
            jPnNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnNhaCungCapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPnLoaiSP.setBackground(new java.awt.Color(76, 175, 80));

        jLbLoaiSP.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbLoaiSP.setForeground(new java.awt.Color(255, 255, 255));
        jLbLoaiSP.setText("Loại sản phẩm");

        javax.swing.GroupLayout jPnLoaiSPLayout = new javax.swing.GroupLayout(jPnLoaiSP);
        jPnLoaiSP.setLayout(jPnLoaiSPLayout);
        jPnLoaiSPLayout.setHorizontalGroup(
            jPnLoaiSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnLoaiSPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnLoaiSPLayout.setVerticalGroup(
            jPnLoaiSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnLoaiSPLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPnMenuLayout = new javax.swing.GroupLayout(jPnMenu);
        jPnMenu.setLayout(jPnMenuLayout);
        jPnMenuLayout.setHorizontalGroup(
            jPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnBanHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnNhapHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnLoaiSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnMenuLayout.setVerticalGroup(
            jPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnMenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPnNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPnLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnViewLayout = new javax.swing.GroupLayout(jPnView);
        jPnView.setLayout(jPnViewLayout);
        jPnViewLayout.setHorizontalGroup(
            jPnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        jPnViewLayout.setVerticalGroup(
            jPnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPnRootLayout = new javax.swing.GroupLayout(jPnRoot);
        jPnRoot.setLayout(jPnRootLayout);
        jPnRootLayout.setHorizontalGroup(
            jPnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnRootLayout.createSequentialGroup()
                .addComponent(jPnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnRootLayout.setVerticalGroup(
            jPnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLbBanHang;
    private javax.swing.JLabel jLbKhachHang;
    private javax.swing.JLabel jLbLoaiSP;
    private javax.swing.JLabel jLbNhaCungCap;
    private javax.swing.JLabel jLbNhanVien;
    private javax.swing.JLabel jLbNhapHang;
    private javax.swing.JLabel jLbSanPham;
    private javax.swing.JLabel jLbThongKe;
    private javax.swing.JPanel jPnBanHang;
    private javax.swing.JPanel jPnKhachHang;
    private javax.swing.JPanel jPnLoaiSP;
    private javax.swing.JPanel jPnMenu;
    private javax.swing.JPanel jPnNhaCungCap;
    private javax.swing.JPanel jPnNhanVien;
    private javax.swing.JPanel jPnNhapHang;
    private javax.swing.JPanel jPnRoot;
    private javax.swing.JPanel jPnSanPham;
    private javax.swing.JPanel jPnThongKe;
    private javax.swing.JPanel jPnView;
    // End of variables declaration//GEN-END:variables
}
